// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6xBz3l8Mj9jM6hOj_yXfkdM98go542s',
    appId: '1:906297067880:web:62d3cd5bdefbcdf4cc6edd',
    messagingSenderId: '906297067880',
    projectId: 'tweet-app-a825e',
    authDomain: 'tweet-app-a825e.firebaseapp.com',
    storageBucket: 'tweet-app-a825e.appspot.com',
    measurementId: 'G-VTJV2R0TB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-xD0o3vfcL9mqgJkvoh7SaVt32f9Yh0M',
    appId: '1:906297067880:android:79197d98c1c80d02cc6edd',
    messagingSenderId: '906297067880',
    projectId: 'tweet-app-a825e',
    storageBucket: 'tweet-app-a825e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bP5B18O33wuLJIjSrqqw3PWdqvaP8dY',
    appId: '1:906297067880:ios:0ebe77cec8ad7636cc6edd',
    messagingSenderId: '906297067880',
    projectId: 'tweet-app-a825e',
    storageBucket: 'tweet-app-a825e.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
